package com.bureauveritas.modelparser.control.file.handler.openapi;

import burp.api.montoya.http.message.params.HttpParameter;
import burp.api.montoya.http.message.requests.HttpRequest;
import com.bureauveritas.modelparser.BurpApi;
import com.bureauveritas.modelparser.control.file.handler.AbstractModelFileHandler;
import com.bureauveritas.modelparser.control.file.serializer.AbstractSerializer;
import com.bureauveritas.modelparser.control.file.serializer.SerializerType;
import com.bureauveritas.modelparser.model.Settings;
import com.bureauveritas.modelparser.view.FontColorUtils;
import com.bureauveritas.modelparser.view.render.HtmlTableCellRenderer;
import io.swagger.v3.oas.models.*;
import io.swagger.v3.oas.models.PathItem.HttpMethod;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.openapitools.codegen.CodegenOperation;
import org.openapitools.codegen.CodegenParameter;
import org.openapitools.codegen.CodegenSecurity;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.util.*;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

// TODO: add control registry for handling specs with multiple options for a field, like requestBody, examples
public class OpenAPIFileHandler extends AbstractModelFileHandler<OpenAPI> {
    private final Pattern operationNamePattern =
        Pattern.compile("^(POST|GET|PUT|PATCH|DELETE|HEAD|OPTIONS|TRACE) (\\S+)(?:\\s+\\(\"([^\"]+)\"\\))?");
    private OpenAPIExamplesExtractor exampleExtractor;

    public static final String UNRESOLVED_MODEL = "unresolved_model";
    private OpenAPI unresolvedModel; // Used for example parsing since the resolved model loses $ref info

    public record ParsedOperationName(String method, String path, String operationId) {}
    
    public OpenAPIFileHandler(OpenAPI modelObject) {
        super(modelObject);
    }

    @Override
    public void setAdditionalProperties(Map<String, Object> additionalProperties) {
        super.setAdditionalProperties(additionalProperties);
        if (additionalProperties.containsKey(UNRESOLVED_MODEL)) {
            unresolvedModel = (OpenAPI) additionalProperties.get(UNRESOLVED_MODEL);
            exampleExtractor = new OpenAPIExamplesExtractor(model, unresolvedModel);
        }
    }

    private enum BodyParamsType {
        BODY_PARAMS, FORM_PARAMS, NONE
    }

    private class OpenAPISerializer extends AbstractSerializer<HttpRequest> {
        private final String contentType;
        private final String exampleRequestBody;

        public OpenAPISerializer(String ct, String erb, String en, String on) {
            super(
                "HTTP Request%s%s".formatted(
                    ct == null ? "" : " (%s)".formatted(ct),
                    en == null ? " (autogenerated)" : " (Example: \"%s\")".formatted(en)
                ),
                SerializerType.HTTP_REQUEST,
                on
            );
            contentType = ct;
            exampleRequestBody = erb;
        }

        @Override
        public HttpRequest serializeRequest(String operationName, boolean includeOptionalParameters) {
            HttpRequest httpRequest = HttpRequest.httpRequest();
            try {
                // Use Codegen since it does additional parsing than the swagger parser
                // Note: Codegen is not meant to be used this way, so some fields may be missing or incorrect;
                // we need to manually handle some fields below
                CodegenOperation operation = getCodegenOperation(operationName);
                httpRequest = httpRequest.withMethod(operation.httpMethod).withPath(operation.path);

                /********** QUERY PARAMS **********/
                // Handle obvious query params
                if (operation.getHasQueryParams()) {
                    httpRequest = httpRequest.withAddedParameters(
                        operation.queryParams.stream().map(param -> {
                            String sampleValue = getSampleParamValue(
                                param, operation.httpMethod, operation.path, "query", null);
                            return HttpParameter.urlParameter(
                                param.baseName,
                                BurpApi.getInstance().utilities().urlUtils().encode(sampleValue)
                            );
                        })
                        .toList());
                }

                /********** HEADER PARAMETERS **********/
                // Handle obvious header params
                if (operation.getHasHeaderParams()) {
                    for (CodegenParameter param : operation.headerParams) {
                        String sampleValue = OpenAPISampleGenerator.getSampleValue(param);
                        httpRequest = httpRequest.withAddedHeader(param.baseName, sampleValue);
                    }
                }
                // Handle Cookie header
                if (operation.getHasCookieParams()) {
                    String cookieValue = getCookieValue(
                        operation,
                        httpRequest.hasHeader("Cookie") ? httpRequest.headerValue("Cookie") : null
                    );
                    httpRequest = httpRequest.withAddedHeader("Cookie", cookieValue);
                }

                // Handle Accept header
                HashSet<String> acceptContentTypes = getResponseContentTypes(operation);
                if (!acceptContentTypes.isEmpty()) {
                    httpRequest = httpRequest.withAddedHeader(
                        "Accept", String.join(",", acceptContentTypes));
                }
                // Add the Host header if missing as Burp requires it for most things
                // validation performed later in applyHost()
                if (!httpRequest.hasHeader("Host")) {
                    httpRequest = httpRequest.withAddedHeader("Host", "");
                }

                /********** REQUEST BODY **********/
                if (contentType != null) {
                    httpRequest = httpRequest.withHeader("Content-Type", contentType);
                }
                if (exampleRequestBody != null) {
                    httpRequest = httpRequest.withBody(exampleRequestBody);
                }
                return httpRequest;
            } catch (Exception e) {
                BurpApi.getInstance().logging().logToError(e);
                return httpRequest.withBody("Error (see Errors log): " + e.getMessage());
            }
        }

        private String getSampleParamValue(
            CodegenParameter param, String method, String path, String in, String contentType
        ) {
            String exampleValue = exampleExtractor.getRandomParameterExample(path, method, param.baseName, in);
            if (exampleValue != null && !exampleValue.isEmpty()) {
                return exampleValue;
            }
            if (contentType != null) {
                // Generate sample value if no example found
                String generatedSample = generateExample(method, path, contentType, false);
                if (generatedSample != null && !generatedSample.isEmpty()) {
                    return generatedSample;
                }
            }
            return OpenAPISampleGenerator.getSampleValue(param);
        }

        private static HashSet<String> getResponseContentTypes(CodegenOperation operation) {
            HashSet<String> responseContentTypes = new HashSet<>();
            if (operation.responses != null) {
                operation.responses.stream()
                    .filter(httpResponse -> httpResponse.getContent() != null)
                    .forEach(httpResponse ->
                        responseContentTypes.addAll(httpResponse.getContent().keySet()));
            }
            // Also try to get content types for Accept from "produces" field (only for OpenAPI v2)
            if (operation.produces != null) {
                operation.produces.stream()
                    .filter(val -> val.containsKey("mediaType"))
                    .forEach(val -> responseContentTypes.add(val.get("mediaType")));
            }
            return responseContentTypes;
        }
    }

    /**
     *
     * @return true if the serializers list has changed
     */
    @Override
    public boolean updateSerializers(String operationName) {
        CodegenOperation op = getCodegenOperation(operationName);
        if (op == null) {
            BurpApi.getInstance().logging().logToError("Warning - Operation not found: " + operationName);
            return false;
        }

        serializers.clear();
        getSerializersForOperation(operationName, op).forEach(this::addSerializer);

        return true;
    }

    @Override
    public List<String> getHosts(String operationName) {
        // Precedence is: Operation level -> Path level -> Global level
        List<String> hosts = new ArrayList<>();
        ParsedOperationName parsedOpName = getOperationComponent(operationName);
        // Operation level
        hosts.addAll(
            Optional.ofNullable(model.getPaths().get(parsedOpName.path()))
                .map(path -> path.readOperationsMap().get(HttpMethod.valueOf(parsedOpName.method())))
                .map(Operation::getServers)
                .orElse(Collections.emptyList())
                .stream()
                .map(Server::getUrl)
                .toList()
        );
        if (!hosts.isEmpty()) {
            return hosts;
        }
        // Path level
        hosts.addAll(
            Optional.ofNullable(model.getPaths().get(parsedOpName.path()))
                .map(PathItem::getServers)
                .orElse(Collections.emptyList())
                .stream()
                .map(Server::getUrl)
                .toList()
        );
        if (!hosts.isEmpty()) {
            return hosts;
        }
        // Global level
        hosts.addAll(model.getServers().stream().map(Server::getUrl).toList());
        return hosts;
    }

    @Override
    public HttpRequest applyHost(String host, HttpRequest httpRequest) {
        if (!Settings.isInvalidOpenAPIHostAllowed()) {
            List<String> validHosts = getHosts(httpRequest.method() + " " + httpRequest.pathWithoutQuery());
            BurpApi.getInstance().logging().logToOutput("Got host %s, expected %s".formatted(httpRequest.headerValue("Host"), validHosts));
            if (!validHosts.isEmpty() && !validHosts.contains(httpRequest.headerValue("Host"))) {
                // Change the Host value to a valid one
                BurpApi.getInstance().logging().logToOutput("   Changing host to %s".formatted(validHosts.getFirst()));
                return super.applyHost(validHosts.getFirst(), httpRequest);
            }
        }
        // Use value as-is, no validation
        return super.applyHost(host, httpRequest);
    }

    @Override
    public HttpRequest applyAuth(String auth, HttpRequest httpRequest) {
        if (auth == null) {
            return httpRequest;
        }
        SecurityScheme securityScheme = model.getComponents().getSecuritySchemes().get(auth);
        return switch (securityScheme.getType()) {
            case APIKEY ->
                switch (securityScheme.getIn()) {
                    case HEADER ->
                        httpRequest.withHeader(securityScheme.getName(), "<AUTH_VALUE>");
                    case QUERY ->
                        httpRequest.withAddedParameters(
                            HttpParameter.urlParameter(securityScheme.getName(), "<AUTH_VALUE>"));
                    case COOKIE ->
                        httpRequest.withAddedParameters(
                            HttpParameter.cookieParameter(securityScheme.getName(), "<AUTH_VALUE>"));
                };
            case HTTP ->
                switch (securityScheme.getScheme().toLowerCase()) {
                    case "basic" -> httpRequest.withAddedHeader(
                        "Authorization",
                        "Basic " + Base64.getEncoder().encodeToString("USER:PASSWORD".getBytes()));
                    case "bearer" -> httpRequest.withAddedHeader(
                        "Authorization",
                        "Bearer %s".formatted(securityScheme.getBearerFormat() != null ?
                            securityScheme.getBearerFormat() :
                            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
                        ));
                    case "digest" -> httpRequest.withAddedHeader(
                        "Authorization",
                        "Digest <DIGEST_VALUE>");
                    default -> httpRequest.withAddedHeader(
                        "Authorization",
                        "<%s_VALUE>".formatted(securityScheme.getScheme().toUpperCase())
                    );
                };
            case OPENIDCONNECT, OAUTH2 -> httpRequest.withAddedHeader(
                "Authorization",
                "Bearer <%s_TOKEN>".formatted(securityScheme.getType().toString().toUpperCase()));
            case MUTUALTLS -> httpRequest;
        };
    }

    private List<OpenAPISerializer> getSerializersForOperation(String operationName, CodegenOperation op) {
        List<OpenAPISerializer> result = new ArrayList<>();
        // Create a serializer for each content type, example, and auth
        getRequestContentTypesExamplesMap(op).forEach((bodyParamsType, contentTypeExamplesMap) ->
            contentTypeExamplesMap.forEach((contentType, examplesMap) -> {
                // Add a serializer for each example
                examplesMap.forEach((exampleName, exampleValue) ->
                    result.add(new OpenAPISerializer(
                        contentType,
                        exampleValue,
                        exampleName,
                        operationName
                    ))
                );
                // Add a generated request body
                result.add(new OpenAPISerializer(
                    contentType,
                    generateExample(op.httpMethod, op.path, contentType, op.getHasFormParams()),
                    null,
                    operationName
                ));
            })
        );
        if (result.isEmpty()) {
            // If result is empty, this operation has no request body
            result.add(new OpenAPISerializer(null, null, null, operationName));
        }

        return result;
    }

    @Override
    public List<String> getAuthOptions(String operationName) {
        List<String> authOptions = new ArrayList<>();
        ParsedOperationName parsedOpName = getOperationComponent(operationName);

        // Global level
        Optional.ofNullable(model.getSecurity())
            .ifPresent(authList ->
                authList.forEach(auth -> authOptions.addAll(auth.keySet())));

        // Note: security cannot be defined Path level

        // Operation level
        Optional.ofNullable(model.getPaths().get(parsedOpName.path())
                .readOperationsMap()
                .get(HttpMethod.valueOf(parsedOpName.method()))
                .getSecurity())
            .ifPresent(authList ->
                authList.forEach(auth -> authOptions.addAll(auth.keySet())));

        return authOptions;
    }

    /**
     * returns Map with "bodyParams" and "formParams" mapping contenttypes to examples
     * {type: {contentType: {exampleName: example}}}
     */
    private Map<BodyParamsType,Map<String,Map<String,String>>>
    getRequestContentTypesExamplesMap(CodegenOperation op) {
        // TODO: return type could be better as a class or record
        HashMap<BodyParamsType, Map<String,Map<String,String>>> result = new HashMap<>();
        Map<String,Map<String,String>> bodyParamsExamplesMap = new HashMap<>(); // {contentType: {exampleName: example}}
        Map<String,Map<String,String>> formParamsExamplesMap = new HashMap<>(); // {contentType: {exampleName: example}}
        if (op.getHasBodyParam()) {
            op.bodyParam.getContent().keySet()
                .forEach(contentType ->
                    bodyParamsExamplesMap.computeIfAbsent(contentType, k -> new HashMap<>())
                        .putAll(exampleExtractor.getRequestBodyExamples(op.path, op.httpMethod, contentType))
                );
        }
        if (op.getHasFormParams()) {
            if (op.consumes != null) {
                op.consumes.stream()
                    .filter(c -> c.containsKey("mediaType"))
                    .map(c -> c.get("mediaType"))
                    .forEach(contentType ->
                        formParamsExamplesMap.computeIfAbsent(contentType, k -> new HashMap<>())
                            .putAll(exampleExtractor.getRequestBodyExamples(op.path, op.httpMethod, contentType, true))
                    );
            }
        }
        result.put(BodyParamsType.BODY_PARAMS, bodyParamsExamplesMap);
        result.put(BodyParamsType.FORM_PARAMS, formParamsExamplesMap);
        return result;
    }

    private static String getCookieValue(CodegenOperation operation, String existingValue) {
        StringBuilder cookieBuilder = new StringBuilder();
        if (existingValue != null) {
            // Make sure not to drop any existing Cookie header value
            cookieBuilder.append(existingValue);
        }
        for (CodegenParameter param : operation.cookieParams) {
            String sampleValue = OpenAPISampleGenerator.getSampleValue(param);
            if (!cookieBuilder.isEmpty()) {
                cookieBuilder.append("; ");
            }
            cookieBuilder.append(String.format("%s=%s", param.baseName, sampleValue));
        }
        // Handle authMethods in cookies
        if (operation.hasAuthMethods) {
            for (CodegenSecurity authMethod : operation.authMethods) {
                if (!authMethod.isKeyInCookie) {
                    continue;
                }
                String sampleValue = authMethod.scheme != null ? authMethod.scheme : authMethod.type;
                if (!cookieBuilder.isEmpty()) {
                    cookieBuilder.append("; ");
                }
                cookieBuilder.append(String.format("%s=%s", authMethod.keyParamName, sampleValue));
            }
        }
        return cookieBuilder.toString();
    }

    private String generateExample(String method, String path, String contentType, boolean isFormData) {
        return OpenAPIExampleGenerator.generate(
            model,
            unresolvedModel,
            method,
            path,
            contentType,
            isFormData
        );
    }

    private ParsedOperationName parseOperationName(String operationName) {
        // FIXME: using a formatted String to pass 3 values is not good
        Matcher matcher = operationNamePattern.matcher(operationName);
        if (matcher.find()) {
            return new ParsedOperationName(
                matcher.group(1),
                matcher.group(2),
                matcher.group(3)
            );
        }
        BurpApi.getInstance().logging().logToError("Warning - operationName did not match regex");
        return null;
    }

    private boolean isOperationExistsInModel(ParsedOperationName parsedOperationName) {
        PathItem pathItem = model.getPaths().get(parsedOperationName.path());
        return pathItem != null &&
            pathItem.readOperationsMap().containsKey(HttpMethod.valueOf(parsedOperationName.method()));
    }


    private ParsedOperationName getOperationComponent(String operationName) {
        ParsedOperationName parsedOperationName = parseOperationName(operationName);
        if (parsedOperationName == null) {
            return null;
        }
        if (!isOperationExistsInModel(parsedOperationName)) {
            System.err.println("Warning - Operation not found");
        }
        return parsedOperationName;
    }

    private CodegenOperation getCodegenOperation(String operationName) {
        ParsedOperationName parsedOperationName = getOperationComponent(operationName);
        if (parsedOperationName == null) {
            return null;
        }
        return OpenAPIUtils.getCodegenOperation(parsedOperationName.path(), parsedOperationName.method(), model);
    }

    @Override
    public List<String> getOperations() {
        Paths paths = model.getPaths();
        if (paths == null || paths.isEmpty()) {
            return List.of();
        }
        return paths.entrySet().stream()
            .flatMap(entry -> {
                String path = entry.getKey();
                PathItem pathItem = entry.getValue();
                return pathItem.readOperationsMap().entrySet().stream()
                    .map(operationEntry -> {
                        String method = operationEntry.getKey().name();
                        Operation operation = operationEntry.getValue();
                        String operationId = operation.getOperationId();
                        // getOperationId() returns "null" if DNE. Don't include this
                        // note: we lose the operationId if it's actually string "null"
                        operationId = operationId == null || operationId.equals("null") ? "" : operationId;
                        return String.format(
                            "%s %s%s", // FIXME: using a formatted String to pass 3 values is not good
                            method,
                            path,
                            Objects.requireNonNullElse(String.format(" (\"%s\")", operationId), "")
                        );
                    });
            })
            .collect(Collectors.toList());
    }

    @Override
    public List<String> getShapeNames() {
        ArrayList<String> shapeList = new ArrayList<>();
        Components components = model.getComponents();
        if (components != null) {
            // See https://swagger.io/specification/#components-object
            if (components.getSchemas() != null) {
                // Add components.schemas definitions
                shapeList.addAll(components.getSchemas().keySet());
            }
            if (components.getParameters() != null) {
                // Add components.parameters definitions
                shapeList.addAll(components.getParameters().keySet());
            }
            if (components.getRequestBodies() != null) {
                // Add components.requestBodies definitions
                shapeList.addAll(components.getRequestBodies().keySet());
            }
            if (components.getExamples() != null) {
                // Add components.examples definitions
                shapeList.addAll(components.getExamples().keySet());
            }
            if (components.getSecuritySchemes() != null) {
                shapeList.addAll(components.getSecuritySchemes().keySet());
            }
        }
        shapeList.addAll(model.getPaths().keySet().stream().filter(path -> {
            String pathParameters = queryJMESPathOnFileContent(String.format("paths.\"%s\".parameters", path));
            return pathParameters != null && !pathParameters.isEmpty();
        }).toList());
        return shapeList;
    }

    @Override
    public String getServiceName() {
        return model.getInfo().getTitle();
    }

    @Override
    public String getModelType() {
        // openapi field (OpenAPI v3)
        String version = queryJMESPathOnFileContent("openapi");
        if (version != null) {
            return "OpenAPI v%s".formatted(version.replace("\"", ""));
        }
        // swagger field (OpenAPI v2)
        version = queryJMESPathOnFileContent("swagger");
        if (version != null) {
            return "OpenAPI/Swagger v%s".formatted(version.replace("\"", ""));
        }
        return "OpenAPI";
    }

    @Override
    public String getOperationMethod(String operationName) {
        ParsedOperationName parsedOperationName = getOperationComponent(operationName);
        if (parsedOperationName == null) return null;
        return parsedOperationName.method();
    }

    @Override
    public String getOperationDefinition(String operationName) {
        ParsedOperationName parsedOperationName = parseOperationName(operationName);
        if (parsedOperationName == null) {
            return null;
        }

        return queryJMESPathOnFileContent(
            String.format("paths.\"%s\".\"%s\"", parsedOperationName.path(), parsedOperationName.method().toLowerCase()));
    }

    @Override
    public String getOperationPath(String operationName) {
        ParsedOperationName parsedOperationName = getOperationComponent(operationName);
        if (parsedOperationName == null) {
            return null;
        }
        return parsedOperationName.path();
    }

    @Override
    public String getOperationShapeName(String operationName) {
        ParsedOperationName parsedOperationName = parseOperationName(operationName);
        if (parsedOperationName == null) {
            return null;
        }
        return parsedOperationName.path();
    }

    @Override
    public Object serializeOperation(
        String operationName,
        AbstractSerializer<?> serializer,
        boolean includeOptionalParameters
    ) {
        // Calling sendToTool on multiple operations often has different serializers,
        // so we need to validate that the serializer matches the operation.
        // If it does not, we select the last autogenerated serializer
        if (!serializer.getOperationName().equals(operationName)) {
            BurpApi.getInstance().logging().logToOutput(
                "Got operation name '%s', but serializer is '%s'".formatted(operationName, serializer.getOperationName()));
            BurpApi.getInstance().logging().logToOutput("Selecting correct serializer...");
            List<OpenAPISerializer> openAPISerializers =
                getSerializersForOperation(operationName, getCodegenOperation(operationName));
            // TODO: rather than creating and selecting from all possible serializers, create only the autogenerated
            return openAPISerializers.getLast() // getLast() should be the autogenerated serializer
                .serializeRequest(operationName, includeOptionalParameters);
        }
        return serializer.serializeRequest(operationName, includeOptionalParameters);
    }

    @Override
    public String getShapeDefinition(String shapeName) {
        if (shapeName == null || shapeName.isEmpty()) {
            return null;
        }
        // Try components schema
        String queryResult = queryJMESPathOnFileContent(String.format("components.schemas.\"%s\"", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        // Try components parameter
        queryResult = queryJMESPathOnFileContent(String.format("components.parameters.\"%s\"", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        // Try components requestBodies
        queryResult = queryJMESPathOnFileContent(String.format("components.requestBodies.\"%s\"", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        // Try components examples
        queryResult = queryJMESPathOnFileContent(String.format("components.examples.\"%s\"", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        // Try top-level path parameters
        queryResult = queryJMESPathOnFileContent(String.format("paths.\"%s\".parameters", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        // OpenAPI v2 specific checks
        // Try definitions
        queryResult = queryJMESPathOnFileContent(String.format("definitions.\"%s\"", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        // Try parameters
        queryResult = queryJMESPathOnFileContent(String.format("parameters.\"%s\"", shapeName));
        if (queryResult != null) {
            return queryResult;
        }
        queryResult = queryJMESPathOnFileContent(String.format("components.securitySchemes.\"%s\"", shapeName));

        return queryResult;
    }

    @Override
    public DefaultTableCellRenderer getOperationsTableCellRenderer() {
        return new HtmlTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column
            ) {
                super.getTableCellRendererComponent(
                    table, getFormattedOperationName((String) value), isSelected, hasFocus, row, column);

                return this;
            }
        };
    }

    @Override
    public String getFormattedOperationName(String operationName) {
        ParsedOperationName parsedOperationName = parseOperationName(operationName);
        if (parsedOperationName == null ||
            parsedOperationName.operationId == null ||
            parsedOperationName.operationId.isEmpty()
        ) {
            return "%s %s".formatted(parsedOperationName.method(), parsedOperationName.path());
        }
        return "<html>%s %s &nbsp;<span color=\"%s\"><i>%s</i></span></html>".formatted(
            parsedOperationName.method(),
            parsedOperationName.path(),
            FontColorUtils.lighterHex(UIManager.getColor("Label.foreground"), 0.5f),
            parsedOperationName.operationId()
        );
    }
}
