# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_serializer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18request_serializer.proto\"D\n\x17SerializeRequestRequest\x12\x11\n\tmodel_str\x18\x01 \x01(\t\x12\x16\n\x0eoperation_name\x18\x02 \x01(\t\"\xa9\x02\n\x18SerializeRequestResponse\x12\x10\n\x08url_path\x18\x01 \x01(\t\x12@\n\x0cquery_string\x18\x02 \x03(\x0b\x32*.SerializeRequestResponse.QueryStringEntry\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x37\n\x07headers\x18\x04 \x03(\x0b\x32&.SerializeRequestResponse.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x05 \x01(\x0c\x1a\x32\n\x10QueryStringEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32^\n\x11RequestSerializer\x12I\n\x10SerializeRequest\x12\x18.SerializeRequestRequest\x1a\x19.SerializeRequestResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_serializer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERIALIZEREQUESTRESPONSE_QUERYSTRINGENTRY']._loaded_options = None
  _globals['_SERIALIZEREQUESTRESPONSE_QUERYSTRINGENTRY']._serialized_options = b'8\001'
  _globals['_SERIALIZEREQUESTRESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_SERIALIZEREQUESTRESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_SERIALIZEREQUESTREQUEST']._serialized_start=28
  _globals['_SERIALIZEREQUESTREQUEST']._serialized_end=96
  _globals['_SERIALIZEREQUESTRESPONSE']._serialized_start=99
  _globals['_SERIALIZEREQUESTRESPONSE']._serialized_end=396
  _globals['_SERIALIZEREQUESTRESPONSE_QUERYSTRINGENTRY']._serialized_start=298
  _globals['_SERIALIZEREQUESTRESPONSE_QUERYSTRINGENTRY']._serialized_end=348
  _globals['_SERIALIZEREQUESTRESPONSE_HEADERSENTRY']._serialized_start=350
  _globals['_SERIALIZEREQUESTRESPONSE_HEADERSENTRY']._serialized_end=396
  _globals['_REQUESTSERIALIZER']._serialized_start=398
  _globals['_REQUESTSERIALIZER']._serialized_end=492
# @@protoc_insertion_point(module_scope)
